[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/connect"
  to = "/links"
  status = 301

[[redirects]]
  from = "/legal/imprint"
  to = "https://hmlabs.eu/legal/imprint"
  status = 301

[[redirects]]
  from = "/legal/privacy"
  to = "https://hmlabs.eu/legal/privacy"
  status = 301

# Redirect von jumpstone4477.de auf henrymeyer.de
[[redirects]]
  from = "https://jumpstone4477.de/*"
  to = "https://henrymeyer.de/:splat"
  status = 301
  force = true

# Redirect von www.jumpstone4477.de auf henrymeyer.de
[[redirects]]
  from = "https://www.jumpstone4477.de/*"
  to = "https://henrymeyer.de/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Onion-Location = "http://2bhhtuncptca3p3spmvs3ctgz4s533fomrhotw32lavqko4emr7ruoid.onion/*"
